"""initial schema

Revision ID: 92f0cac4322f
Revises: 
Create Date: 2026-07-24 19:14:44.983268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '92f0cac4322f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before the knowledge_embeddings VECTOR column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'cancelled', name='companystatus'), nullable=False),
    sa.Column('icp_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('model_registry_entries',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('training', 'active', 'archived', name='modelstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_entries_model_name'), 'model_registry_entries', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_registry_entries_model_version'), 'model_registry_entries', ['model_version'], unique=True)
    op.create_index(op.f('ix_model_registry_entries_status'), 'model_registry_entries', ['status'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('user_limit', sa.Integer(), nullable=True),
    sa.Column('ai_credit_limit', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_company_id'), 'billing_subscriptions', ['company_id'], unique=False)
    op.create_table('campaign_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='templatestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_templates_company_id'), 'campaign_templates', ['company_id'], unique=False)
    op.create_table('integrations',
    sa.Column('integration_type', sa.Enum('crm', 'email', 'calendar', 'chat', name='integrationtype'), nullable=False),
    sa.Column('provider', sa.Enum('salesforce', 'hubspot', 'zoho', 'gmail', 'google_calendar', 'slack', name='integrationprovider'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='connectionstatus'), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_company_id'), 'integrations', ['company_id'], unique=False)
    op.create_table('revenue_forecasts',
    sa.Column('forecast_period', sa.String(), nullable=False),
    sa.Column('predicted_revenue', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_forecasts_company_id'), 'revenue_forecasts', ['company_id'], unique=False)
    op.create_index(op.f('ix_revenue_forecasts_forecast_period'), 'revenue_forecasts', ['forecast_period'], unique=False)
    op.create_table('usage_records',
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_billing_period'), 'usage_records', ['billing_period'], unique=False)
    op.create_index(op.f('ix_usage_records_company_id'), 'usage_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_type'), 'usage_records', ['usage_type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'sales_manager', 'sales_executive', 'marketing', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('business', 'security', name='auditcategory'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('target_industry', sa.String(), nullable=True),
    sa.Column('target_region', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaignstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_company_id'), 'campaigns', ['company_id'], unique=False)
    op.create_table('integration_sync_logs',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'retrying', name='syncstatus'), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_logs_company_id'), 'integration_sync_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_integration_sync_logs_integration_id'), 'integration_sync_logs', ['integration_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_category', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='documentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_company_id'), 'knowledge_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'researching', 'ready', 'contacted', 'demo_scheduled', 'proposal', 'closed_won', 'closed_lost', name='leadstatus'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='leadpriority'), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('external_crm_source', sa.String(), nullable=True),
    sa.Column('external_crm_id', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_archived_at'), 'leads', ['archived_at'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_external_crm_id'), 'leads', ['external_crm_id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('ai_interaction_logs',
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interaction_logs_agent_name'), 'ai_interaction_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_interaction_logs_company_id'), 'ai_interaction_logs', ['company_id'], unique=False)
    op.create_table('ai_research_reports',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('industry_insights', sa.Text(), nullable=True),
    sa.Column('company_size_estimate', sa.String(), nullable=True),
    sa.Column('recent_news', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_research_reports_company_id'), 'ai_research_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_research_reports_lead_id'), 'ai_research_reports', ['lead_id'], unique=False)
    op.create_table('audience_segments',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('min_employees', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_lead_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_campaign_id'), 'audience_segments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_audience_segments_company_id'), 'audience_segments', ['company_id'], unique=False)
    op.create_table('buying_signals',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_signals_company_id'), 'buying_signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_buying_signals_lead_id'), 'buying_signals', ['lead_id'], unique=False)
    op.create_table('contacts',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_archived_at'), 'contacts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_lead_id'), 'contacts', ['lead_id'], unique=False)
    # `deals` is created BEFORE `deal_outcomes` and `crm_activities`: both now
    # carry a FK to deals.id, so the parent table must already exist.
    op.create_table('deals',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('new', 'qualified', 'demo_scheduled', 'proposal_sent', 'negotiation', 'closed_won', 'closed_lost', name='dealstage'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_archived_at'), 'deals', ['archived_at'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_table('deal_outcomes',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.Enum('won', 'lost', name='outcome'), nullable=False),
    sa.Column('loss_reason', sa.Enum('budget_constraint', 'chose_competitor', 'timing', 'no_current_need', 'no_response', 'other', name='lossreason'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_outcomes_company_id'), 'deal_outcomes', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_outcomes_deal_id'), 'deal_outcomes', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_outcomes_lead_id'), 'deal_outcomes', ['lead_id'], unique=False)
    op.create_table('crm_activities',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activities_company_id'), 'crm_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_deal_id'), 'crm_activities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_lead_id'), 'crm_activities', ['lead_id'], unique=False)
    op.create_table('icp_scores',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('industry_score', sa.Float(), nullable=False),
    sa.Column('company_size_score', sa.Float(), nullable=False),
    sa.Column('region_score', sa.Float(), nullable=False),
    sa.Column('pain_point_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_scores_company_id'), 'icp_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_icp_scores_lead_id'), 'icp_scores', ['lead_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_company_id'), 'knowledge_chunks', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('positive_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('negative_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('baseline_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_company_id'), 'lead_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_table('meetings',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('meeting_type', sa.Enum('discovery', 'demo', 'follow_up', 'negotiation', 'other', name='meetingtype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'rescheduled', name='meetingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('next_action', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_company_id'), 'meetings', ['company_id'], unique=False)
    op.create_index(op.f('ix_meetings_lead_id'), 'meetings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_owner_id'), 'meetings', ['owner_id'], unique=False)
    op.create_table('notes',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_company_id'), 'notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_notes_deal_id'), 'notes', ['deal_id'], unique=False)
    op.create_index(op.f('ix_notes_lead_id'), 'notes', ['lead_id'], unique=False)
    op.create_table('rag_retrieval_logs',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.Text(), nullable=False),
    sa.Column('used_for', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieval_logs_company_id'), 'rag_retrieval_logs', ['company_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'sent', name='draftstatus'), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('rag_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_company_id'), 'email_drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_lead_id'), 'email_drafts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_status'), 'email_drafts', ['status'], unique=False)
    op.create_table('knowledge_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_company_id'), 'knowledge_embeddings', ['company_id'], unique=False)
    op.create_table('sent_emails',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_emails_company_id'), 'sent_emails', ['company_id'], unique=False)
    op.create_index(op.f('ix_sent_emails_draft_id'), 'sent_emails', ['draft_id'], unique=False)
    op.create_index(op.f('ix_sent_emails_lead_id'), 'sent_emails', ['lead_id'], unique=False)
    op.create_table('replies',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('sent_email_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['sent_email_id'], ['sent_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_company_id'), 'replies', ['company_id'], unique=False)
    op.create_index(op.f('ix_replies_lead_id'), 'replies', ['lead_id'], unique=False)
    op.create_table('reply_intent_results',
    sa.Column('reply_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.Enum('interested', 'follow_up', 'rejected', 'info_request', name='replyintent'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_intent_results_company_id'), 'reply_intent_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_reply_intent_results_lead_id'), 'reply_intent_results', ['lead_id'], unique=False)
    op.create_index(op.f('ix_reply_intent_results_reply_id'), 'reply_intent_results', ['reply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_intent_results_reply_id'), table_name='reply_intent_results')
    op.drop_index(op.f('ix_reply_intent_results_lead_id'), table_name='reply_intent_results')
    op.drop_index(op.f('ix_reply_intent_results_company_id'), table_name='reply_intent_results')
    op.drop_table('reply_intent_results')
    op.drop_index(op.f('ix_replies_lead_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_company_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_sent_emails_lead_id'), table_name='sent_emails')
    op.drop_index(op.f('ix_sent_emails_draft_id'), table_name='sent_emails')
    op.drop_index(op.f('ix_sent_emails_company_id'), table_name='sent_emails')
    op.drop_table('sent_emails')
    op.drop_index(op.f('ix_knowledge_embeddings_company_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    op.drop_index(op.f('ix_email_drafts_status'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_lead_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_company_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_rag_retrieval_logs_company_id'), table_name='rag_retrieval_logs')
    op.drop_table('rag_retrieval_logs')
    op.drop_index(op.f('ix_notes_lead_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_deal_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_company_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_owner_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_lead_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_company_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_company_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_company_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_icp_scores_lead_id'), table_name='icp_scores')
    op.drop_index(op.f('ix_icp_scores_company_id'), table_name='icp_scores')
    op.drop_table('icp_scores')
    # Everything holding a FK to deals.id drops FIRST: deal_outcomes and
    # crm_activities. (`notes` also references deals.id and is dropped above.)
    op.drop_index(op.f('ix_deal_outcomes_lead_id'), table_name='deal_outcomes')
    op.drop_index(op.f('ix_deal_outcomes_deal_id'), table_name='deal_outcomes')
    op.drop_index(op.f('ix_deal_outcomes_company_id'), table_name='deal_outcomes')
    op.drop_table('deal_outcomes')
    op.drop_index(op.f('ix_crm_activities_lead_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_deal_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_company_id'), table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_archived_at'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_contacts_lead_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_archived_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_buying_signals_lead_id'), table_name='buying_signals')
    op.drop_index(op.f('ix_buying_signals_company_id'), table_name='buying_signals')
    op.drop_table('buying_signals')
    op.drop_index(op.f('ix_audience_segments_company_id'), table_name='audience_segments')
    op.drop_index(op.f('ix_audience_segments_campaign_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_ai_research_reports_lead_id'), table_name='ai_research_reports')
    op.drop_index(op.f('ix_ai_research_reports_company_id'), table_name='ai_research_reports')
    op.drop_table('ai_research_reports')
    op.drop_index(op.f('ix_ai_interaction_logs_company_id'), table_name='ai_interaction_logs')
    op.drop_index(op.f('ix_ai_interaction_logs_agent_name'), table_name='ai_interaction_logs')
    op.drop_table('ai_interaction_logs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_archived_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_crm_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_company_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_integration_sync_logs_integration_id'), table_name='integration_sync_logs')
    op.drop_index(op.f('ix_integration_sync_logs_company_id'), table_name='integration_sync_logs')
    op.drop_table('integration_sync_logs')
    op.drop_index(op.f('ix_campaigns_company_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_usage_type'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_company_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_billing_period'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_revenue_forecasts_forecast_period'), table_name='revenue_forecasts')
    op.drop_index(op.f('ix_revenue_forecasts_company_id'), table_name='revenue_forecasts')
    op.drop_table('revenue_forecasts')
    op.drop_index(op.f('ix_integrations_company_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_campaign_templates_company_id'), table_name='campaign_templates')
    op.drop_table('campaign_templates')
    op.drop_index(op.f('ix_billing_subscriptions_company_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_model_registry_entries_status'), table_name='model_registry_entries')
    op.drop_index(op.f('ix_model_registry_entries_model_version'), table_name='model_registry_entries')
    op.drop_index(op.f('ix_model_registry_entries_model_name'), table_name='model_registry_entries')
    op.drop_table('model_registry_entries')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Hand-added, not autogenerated. Alembic emits CREATE TYPE on upgrade but
    # never the matching DROP TYPE on downgrade, so `downgrade base` followed
    # by `upgrade head` fails with 'type "role" already exists'. Dropped after
    # the tables, since a type cannot be dropped while a column still uses it.
    # The `vector` extension is deliberately left in place: CREATE EXTENSION
    # IF NOT EXISTS is idempotent, and other schemas in the database may rely
    # on it.
    for enum_name in (
        'auditcategory',
        'campaignstatus',
        'companystatus',
        'connectionstatus',
        'dealstage',
        'documentstatus',
        'draftstatus',
        'integrationprovider',
        'integrationtype',
        'jobstatus',
        'leadpriority',
        'leadstatus',
        'lossreason',
        'meetingstatus',
        'meetingtype',
        'modelstatus',
        'outcome',
        'replyintent',
        'role',
        'subscriptionstatus',
        'syncstatus',
        'templatestatus',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')