"""How much a human changed what the AI wrote.

This is the platform's most valuable feedback signal, because it costs a rep
nothing to produce: they edit the draft because they were going to edit it
anyway. A five-star rating requires someone to stop and rate; an edit distance
is generated by the work itself.

**It is only measurable if the AI's original text still exists.** Until Module
13, `outreach_service.update_draft` overwrote `EmailDraft.body` in place, so
the first human keystroke destroyed the thing we needed to compare against and
every edit-distance metric would silently have been computed over a draft
comparing to itself. `EmailDraft.ai_original_subject`/`ai_original_body` exist
for exactly this, snapshotted on first edit.

Measured on **words, not characters**. Character distance reports a large
change when a rep swaps "Hi" for "Hello" and a small one when they invert the
meaning of a sentence; words track what a reader would call an edit. `difflib`
is stdlib, so this costs no dependency — and a Levenshtein package would buy
precision this metric does not need, since the output is bucketed anyway.
"""

import re
from difflib import SequenceMatcher
from typing import Any

# Distance bands. The brief's worked example — a rep changing the greeting and
# the CTA — lands around 0.12 and should read as a *good* draft that needed
# polish, not as a failure. A rewrite is the signal that matters, and it has to
# be distinguishable from a tidy-up.
LIGHT_EDIT_MAX = 0.15
MODERATE_EDIT_MAX = 0.40
HEAVY_EDIT_MAX = 0.70

VERDICT_ACCEPTED = "accepted_verbatim"
VERDICT_LIGHT = "light_edit"
VERDICT_MODERATE = "moderate_edit"
VERDICT_HEAVY = "heavy_edit"
VERDICT_REWRITTEN = "rewritten"

_WORD_RE = re.compile(r"\w+(?:'\w+)?")


def tokenize(text: str | None) -> list[str]:
    """Lowercased word tokens.

    Case and punctuation are dropped deliberately: "Hi Rahul," to "Hi Rahul"
    is not a human disagreeing with the AI, and counting it as one would put
    noise into the metric that decides whether a prompt is working.
    """

    return _WORD_RE.findall((text or "").lower())


def verdict_for(distance: float) -> str:
    if distance <= 0.0:
        return VERDICT_ACCEPTED
    if distance <= LIGHT_EDIT_MAX:
        return VERDICT_LIGHT
    if distance <= MODERATE_EDIT_MAX:
        return VERDICT_MODERATE
    if distance <= HEAVY_EDIT_MAX:
        return VERDICT_HEAVY
    return VERDICT_REWRITTEN


def measure(
    *,
    original_subject: str | None,
    original_body: str | None,
    final_subject: str | None,
    final_body: str | None,
) -> dict[str, Any]:
    """Compare the AI's draft with what the human actually approved.

    Subject and body are measured separately as well as combined. They fail
    differently and are fixed by different prompt changes: a subject line
    rewritten every time is a subject-prompt problem, and averaging it into a
    400-word body would hide it completely — a fully rewritten subject moves
    the combined figure by a couple of percent.
    """

    original_words = tokenize(original_body)
    final_words = tokenize(final_body)
    subject_original = tokenize(original_subject)
    subject_final = tokenize(final_subject)

    body_distance = _distance(original_words, final_words)
    subject_distance = _distance(subject_original, subject_final)

    # Weighted by length so the combined figure means "what fraction of the
    # words the AI produced did a human change", rather than treating a
    # six-word subject as half the draft.
    total_original = len(original_words) + len(subject_original)
    if total_original:
        combined = (
            body_distance * len(original_words) + subject_distance * len(subject_original)
        ) / total_original
    else:
        combined = subject_distance if subject_original or subject_final else body_distance

    return {
        "edit_distance": round(combined, 4),
        "body_distance": round(body_distance, 4),
        "subject_distance": round(subject_distance, 4),
        "subject_changed": subject_distance > 0,
        "original_word_count": len(original_words),
        "final_word_count": len(final_words),
        "words_added": max(0, len(final_words) - len(original_words)),
        "words_removed": max(0, len(original_words) - len(final_words)),
        "verdict": verdict_for(combined),
    }


def _distance(original: list[str], final: list[str]) -> float:
    """1 - similarity, bounded to [0, 1].

    An empty original with a non-empty final is total divergence (the human
    wrote everything); both empty is no divergence rather than a division by
    zero.
    """

    if not original and not final:
        return 0.0
    if not original or not final:
        return 1.0
    return max(0.0, min(1.0, 1.0 - SequenceMatcher(None, original, final).ratio()))
